[package]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2018"
name = "fe-compiler-test-utils"
version = "0.6.1-alpha"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethabi = "14.0"
evm = "0.26.0"
evm-runtime = "0.26.0"
fe-common = {path = "../common", version = "^0.6.1-alpha"}
fe-driver = {path = "../driver", version = "^0.6.1-alpha"}
fe-yulgen = {path = "../yulgen", version = "^0.6.1-alpha"}
fe-yulc = {path = "../yulc", version = "^0.6.1-alpha", optional = true, features = ["solc-backend"]}
test-files = {path = "../test-files", package = "fe-test-files" }
hex = "0.4"
primitive-types = {version = "0.9", default-features = false, features = ["rlp"]}
serde_json = "1.0.64"
solc = {git = "https://github.com/g-r-a-n-t/solc-rust", optional = true}
stringreader = "0.1"
yultsur = {git = "https://github.com/g-r-a-n-t/yultsur"}

[features]
solc-backend = ["fe-yulc", "solc"]
